### ISSUE TITLE
Dependency on mycroft imports

### ISSUE THREAD

**Issue by PureTryOut** [OpenVoiceOS/skill-ovos-volume#24]
This skill still has dependencies on mycroft imports rather than OVOS ones. In `__init__.py` the following lines are used:

```python
from mycroft.skills.core import MycroftSkill, intent_handler, intent_file_handler
from mycroft.util import normalize
from mycroft.util.parse import extract_number
```

**Comment by emphasize** [comment]
Thanks, will update it.
But should be still supported `ovos-core 0.0.7`, isn't it?

**Comment by JarbasAl** [comment]
> Thanks, will update. But should be still supported `ovos-core 0.0.7`, isn't it?

should be supported until 0.1.0 , but highly recommended to migrate over and it will spam warnings logs left and right
